module.exports = [
  "conceptualise an ~ entity ~ E",
  "conceptualise an ~ imageable thing ~ I that has the value V as ~ image ~",
  "conceptualise a ~ timestamp ~ T that is an entity",
  "conceptualise an ~ agent ~ A that is an entity and has the value V as ~ address ~",
  "conceptualise an ~ individual ~ I that is an ~ agent ~",
  "conceptualise a ~ card ~ C that is an entity and has the timestamp T as ~ timestamp ~ and has the value V as ~ content ~ and has the value W as ~ linked content ~ and has the value V as ~ number of keystrokes ~ and has the timestamp T as ~ start time ~ and has the value W as ~ submit time ~ and has the value L as ~ latitude ~ and has the value M as ~ longitude ~",
  "conceptualise the card C ~ is to ~ the agent A and ~ is from ~ the agent B and ~ is in reply to ~ the card C",
  "conceptualise a ~ tell card ~ T that is a card",
  "conceptualise an ~ ask card ~ A that is a card",
  "conceptualise a ~ gist card ~ G that is a card",
  "conceptualise an ~ nl card ~ N that is a card",
  "conceptualise a ~ confirm card ~ C that is a card",
  "conceptualise a ~ location ~ L that is an entity",
  "conceptualise a ~ locatable thing ~ L that is an entity",
  "conceptualise the locatable thing L ~ is in ~ the location M",
  "conceptualise a ~ rule ~ R that is an entity and has the value V as ~ instruction ~",
  "conceptualise a ~ policy ~ P that is an entity and has the value V as ~ enabled ~ and has the agent A as ~ target ~",
  "conceptualise a ~ tell policy ~ P that is a policy",
  "conceptualise an ~ ask policy ~ P that is a policy",
  "conceptualise a ~ listen policy ~ P that is a policy",
  "conceptualise a ~ listen onbehalfof policy ~ P that is a policy",
  "conceptualise a ~ forwardall policy ~ P that is a policy and has the timestamp T as ~ start time ~ and has the value V as ~ all agents ~",
  "conceptualise a ~ feedback policy ~ P that is a policy and has the value V as ~ acknowledgement ~"
];
